# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Config-Loader
version:      0.01
version_from: lib/Config/Loader.pm
installdirs:  site
requires:
    Config::Find:                  0.16
    Data::Dumper:                  2.121
    Error:                         0.15
    File::Spec:                    0.87
    Getopt::Long:                  2.34
    IO::File:                      1.10

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
